### ISSUE TITLE
关于tableview存在多种cell的问题

### ISSUE THREAD

**Issue by JohnLif** [lovemo/MVVMFramework#1]
请问你写的框架在单个tableview中有多种cell的时候，应该如何写

**Comment by lovemo** [comment]
要弄一个适合大多数人用的东西还有很多细节要完善，以后会添加的。

**Comment by robert121** [comment]
如果你cell的type依赖于dataRequest,同样在viewmodel 里面做request，再刷新，这要求一个viewmodel适配多种cell，这样会导致viewmodel变得庞大。或者在XTableDataDelegate和viewmodel之间再加一层，区分出cell的type，在分发给每个cell对应的viewmodel。如果tableview是静态的话就很简单了

**Comment by lovemo** [comment]
我写了个例子，你们具体的可以根据实际开发需要去改动代码以迎合自己开发的需求

**Comment by Dolion-Hou** [comment]
who tell me what the delegate is ? I always can't understand it .

**Comment by lovemo** [comment]
欢迎加群交流
