### ISSUE TITLE
网络请求缓存机制

### ISSUE THREAD

**Issue by xianhaoyang** [lovemo/MVVMFramework#8]
希望网络请求缓存机制应该像sdwebimage一样可以设置缓存时间

**Comment by lovemo** [comment]
因为网络缓存往往总是伴随着对一些数据的判断，然后去做一些其他的事，例如根据用户的id或者发表内容的时间判断是否有新内容等，如果做统一处理缓存的话，感觉不太好，所以网络缓存功能暂时去掉了，交给自己去处理利用SMKStore缓存到数据库比较好
